name: Build

on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/docker/login@master
      env:
        DOCKER_REGISTRY_URL: docker.debugger.vn
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/docker/cli@master
      with:
        args: build . -t "$DOCKER_REGISTRY_URL/lutos/frontend:$GITHUB_SHA"
      env:
        DOCKER_REGISTRY_URL: docker.debugger.vn

    - uses: actions/docker/cli@master
      with:
        args: push "$DOCKER_REGISTRY_URL/lutos/frontend:$GITHUB_SHA"
      env:
        DOCKER_REGISTRY_URL: docker.debugger.vn
