name: Build

on:
  push:
    branches:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.debugger.vn
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker-compose build
        name: build
        env:
          TAG: $GITHUB_SHA
          DOCKER_REGISTRY: docker.debugger.vn/
      - name: publish
        run: docker-compose push
        env:
          TAG: $GITHUB_SHA
          DOCKER_REGISTRY: docker.debugger.vn/
