name: Build

on:
  push:
    branches:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: login
        run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_REGISTRY_URL: docker.debugger.vn
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build . -t docker.debugger.vn/lutos/frontend:$GITHUB_SHA
        name: build

      - name: publish
        run: docker push docker.debugger.vn/lutos/frontend:$GITHUB_SHA

