name: Build

on:
  push:
    branches:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.debugger.vn
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker://docker/compose:1.24.1
        name: build
        with:
          args: "build"
        env:
          TAG: $GITHUB_SHA
          DOCKER_REGISTRY: docker.debugger.vn/
      - name: publish
        uses: docker://docker/compose:1.24.1
        with:
          args: "push"
        env:
          TAG: $GITHUB_SHA
          DOCKER_REGISTRY: docker.debugger.vn/
